server:
  port: 9090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///springboot
    #mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.clearsky.springboot.entity
  #日志配置
logging:
  level:
    com:
      clearsky:
        springboot:
          mapper: debug
